version: '3.4'

services:

  redis:
     image: mcr.microsoft.com/oss/bitnami/redis:6.0.8

  site.external:
    image: ${DOCKER_REGISTRY-}site
    build:
      context: .
      dockerfile: Site.External/Dockerfile

  api.internal:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Api.Internal/Dockerfile

